# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, unique=True)),
                ('passwd', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('memberid', models.CharField(default=b'', max_length=15)),
                ('id_name', models.CharField(max_length=15, null=True)),
                ('id_no', models.CharField(max_length=15, null=True)),
                ('id_type', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=True)),
                ('phone', models.CharField(db_index=True, default=b'', max_length=50, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='\u90ae\u7bb1')),
                ('is_social', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField()),
                ('username', models.CharField(db_index=True, max_length=12)),
                ('avatar_url', models.CharField(blank=True, max_length=255)),
                ('avatar_name', models.CharField(blank=True, max_length=64)),
                ('mid', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_uid', models.CharField(max_length=128)),
                ('site_name', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_user', to='member.SiteUser')),
            ],
        ),
        migrations.AddField(
            model_name='inneruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inner_user', to='member.SiteUser'),
        ),
        migrations.AlterUniqueTogether(
            name='socialuser',
            unique_together=set([('site_uid', 'site_name')]),
        ),
    ]
