# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-22 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inneruser',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
