# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userid', models.CharField(db_index=True, default=b'', max_length=50, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('username', models.TextField(default='\u9ec4\u5723\u4f1f', max_length=100)),
                ('identifcation', models.IntegerField(default=0)),
                ('usertoken', models.CharField(default=b'', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('mid', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'User',
                'swappable': 'AUTH_USER_MODEL',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(default='hsw', max_length=100)),
                ('memberid', models.CharField(default=b'', max_length=15)),
                ('id_name', models.CharField(max_length=15, null=True)),
                ('id_no', models.CharField(max_length=15, null=True)),
                ('id_type', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=True)),
                ('phone', models.CharField(db_index=True, default=b'', max_length=50, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='\u90ae\u7bb1')),
                ('mid', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
