# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180415_2215'),
        ('users', '0002_auto_20180415_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submerchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Submerchant'),
        ),
    ]
