# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(default='hsw', max_length=100)),
                ('memberid', models.CharField(default=b'', max_length=15)),
                ('id_name', models.CharField(max_length=15, null=True)),
                ('id_no', models.CharField(max_length=15, null=True)),
                ('gender', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
