# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171012_1452'),
        ('users', '0005_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(db_index=True, default=b'', max_length=50, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
