# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171104_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_type',
            field=models.IntegerField(default=0),
        ),
    ]
