# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_member_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='\u90ae\u7bb1'),
        ),
    ]
