# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171012_1452'),
        ('users', '0008_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('orderamount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u8ba2\u5355\u91d1\u989d')),
                ('payedamount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d')),
                ('payment_status', models.SmallIntegerField(verbose_name='\u652f\u4ed8\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.CharField(default=b'', max_length=10)),
                ('proj_name', models.CharField(default=b'', max_length=128)),
                ('mid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
        migrations.AddField(
            model_name='order',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
    ]
