# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171012_1452'),
        ('users', '0009_auto_20171107_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant'),
        ),
    ]
