# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_order_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.CharField(db_index=True, default=users.utils.gettimestamp, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_id',
            field=models.CharField(db_index=True, default=b'', max_length=10),
        ),
    ]
