# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-30 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171109_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='proj',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userinfo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mid',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
