# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikachutest', '0003_auto_20170418_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginfo',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
