# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 16:38
from __future__ import unicode_literals

import commom.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComboRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('proj_id', models.CharField(db_index=True, default='', editable=False, max_length=10, verbose_name='\u670d\u52a1\u7f16\u53f7')),
                ('proj_name', models.CharField(default='', max_length=128)),
                ('user_id', models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('state', models.IntegerField(default=0, verbose_name='\u670d\u52a1\u72b6\u6001')),
                ('create_user', models.CharField(max_length=10, null=True, verbose_name='\u521b\u5efa\u8005')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('cycle_day', models.IntegerField(default=1, verbose_name='\u79df\u8d41\u5468\u671f')),
                ('process_day', models.IntegerField(default=1, verbose_name='\u79df\u8d41\u65f6\u957f')),
                ('guarantee', commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u62bc\u91d1')),
                ('payed_amount', commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u603b\u5171\u652f\u4ed8\u7684\u91d1\u989d')),
                ('changelist', models.CharField(default='', max_length=3000, verbose_name='\u79df\u54c1\u53d8\u5316\u60c5\u51b5')),
            ],
            options={
                'verbose_name': '\u5957\u9910\u79df\u8d41\u670d\u52a1',
                'verbose_name_plural': '\u5957\u9910\u79df\u8d41\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Datapool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantid', models.CharField(db_index=True, default='', max_length=15, verbose_name='\u5546\u6237\u7f16\u53f7')),
                ('datapool', models.TextField(verbose_name='\u6570\u636e\u6c60')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('merchantid', models.CharField(db_index=True, default='10000000123', editable=False, max_length=15, unique=True, verbose_name='\u5546\u6237\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u5546\u6237\u540d\u79f0')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('key', models.CharField(default='', max_length=200, verbose_name='\u5bc6\u94a5')),
                ('expiretime', models.CharField(default='3600', max_length=6, verbose_name='\u6709\u6548\u65f6\u95f4')),
                ('daily_maxcount', models.IntegerField(default=100, verbose_name='\u6bcf\u65e5\u6700\u5927\u8bbf\u95ee\u6b21\u6570')),
            ],
            options={
                'verbose_name': '\u5546\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u5546\u6237\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('orderid', models.CharField(max_length=30, verbose_name='\u8ba2\u5355\u4fe1\u606f')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'permissions': (('view', 'can view the available order'), ('change', 'can change the status')),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('name', models.CharField(default='', max_length=10, verbose_name='\u5957\u9910\u540d\u5b57')),
                ('low_bound', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u4ef7\u683c\u4e0b\u9650')),
                ('high_bound', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u4ef7\u683c\u4e0a\u9650')),
            ],
            options={
                'verbose_name': '\u5957\u9910\u7ba1\u7406',
                'verbose_name_plural': '\u5957\u9910\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('pay_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('order_id', models.CharField(default='0', max_length=20)),
                ('user_id', models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('payedamount', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d')),
            ],
            options={
                'verbose_name': '\u652f\u4ed8\u8ba2\u5355',
                'verbose_name_plural': '\u652f\u4ed8\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('productid', models.CharField(db_index=True, default='0', editable=False, max_length=15, unique=True, verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
                ('productname', models.CharField(max_length=30, null=True, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('category', models.PositiveIntegerField(default=0, verbose_name='\u5546\u54c1\u5206\u7c7b')),
                ('productprice', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u4ea7\u54c1\u552e\u4ef7')),
                ('proddesc', models.CharField(max_length=500, null=True, verbose_name='\u4ea7\u54c1\u63cf\u8ff0')),
                ('inventory', models.IntegerField(default=1000, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('guarantee', commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u62bc\u91d1')),
                ('rentalprice', commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u79df\u8d41\u5355\u4ef7')),
                ('image1', models.ImageField(default='', null=True, upload_to='img/product', verbose_name='\u56fe\u72471')),
                ('image2', models.ImageField(default='', null=True, upload_to='img/product', verbose_name='\u56fe\u72472')),
                ('image3', models.ImageField(default='', null=True, upload_to='img/product', verbose_name='\u56fe\u72473')),
                ('image4', models.ImageField(default='', null=True, upload_to='img/product', verbose_name='\u56fe\u72474')),
                ('image5', models.ImageField(default='', null=True, upload_to='img/product', verbose_name='\u56fe\u72475')),
                ('image6', models.ImageField(default='', null=True, upload_to='img/product', verbose_name='\u56fe\u72476')),
            ],
            options={
                'ordering': ('productid', 'mid'),
                'verbose_name': '\u5546\u54c1\u7ba1\u7406',
                'verbose_name_plural': '\u5546\u54c1\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('itemid', models.CharField(db_index=True, default='0', editable=False, max_length=18, unique=True, verbose_name='\u771f\u5b9e\u4ea7\u54c1ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4ea7\u54c1\u540d\u5b57')),
                ('inventory', models.IntegerField(default=1000, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('attributes', commom.models.JSONField(default={}, verbose_name='\u4ea7\u54c1\u53c2\u6570')),
                ('productprice', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u4ea7\u54c1\u552e\u4ef7')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('proj_id', models.CharField(db_index=True, default='', editable=False, max_length=10, verbose_name='\u670d\u52a1\u7f16\u53f7')),
                ('proj_name', models.CharField(default='', max_length=128)),
                ('user_id', models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('state', models.IntegerField(default=0, verbose_name='\u670d\u52a1\u72b6\u6001')),
                ('create_user', models.CharField(max_length=10, null=True, verbose_name='\u521b\u5efa\u8005')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('cycle_day', models.IntegerField(default=1, verbose_name='\u79df\u8d41\u5468\u671f')),
                ('process_day', models.IntegerField(default=1, verbose_name='\u79df\u8d41\u65f6\u957f')),
                ('guarantee', commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u62bc\u91d1')),
                ('payed_amount', commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u603b\u5171\u652f\u4ed8\u7684\u91d1\u989d')),
            ],
            options={
                'verbose_name': '\u79df\u8d41\u670d\u52a1',
                'verbose_name_plural': '\u79df\u8d41\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('user_id', models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('paytime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('orderamount', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u8ba2\u5355\u91d1\u989d')),
                ('payedamount', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d')),
                ('payment_status', models.SmallIntegerField(verbose_name='\u652f\u4ed8\u72b6\u6001')),
                ('orderid', models.CharField(db_index=True, default=commom.models.gettimestamp, editable=False, max_length=20, unique=True)),
                ('proj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orderid', to='crm.ProductRental')),
            ],
            options={
                'verbose_name': '\u79df\u8d41\u8ba2\u5355',
                'verbose_name_plural': '\u79df\u8d41\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='Submerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('subid', models.CharField(db_index=True, default='0', editable=False, max_length=15, unique=True, verbose_name='\u95e8\u5e97\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u95e8\u5e97\u7ba1\u7406',
                'verbose_name_plural': '\u95e8\u5e97\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='TokenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, verbose_name='\u7528\u6237token')),
                ('count', models.IntegerField(default=0, verbose_name='\u5df2\u8bbf\u95ee\u6b21\u6570')),
                ('max_count', models.IntegerField(default=100, verbose_name='\u6700\u5927\u8bbf\u95ee\u6b21\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='\u7528\u6237\u540d')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('phone', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('vertime', models.CharField(default='', max_length=200, verbose_name='\u9a8c\u8bc1\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Userdata',
                'verbose_name_plural': 'Merchant',
            },
        ),
    ]
