# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-08 15:37
from __future__ import unicode_literals

import commom.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datapool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantid', models.CharField(db_index=True, default='', max_length=15, verbose_name='\u5546\u6237\u7f16\u53f7')),
                ('datapool', models.TextField(verbose_name='\u6570\u636e\u6c60')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('merchantid', models.CharField(db_index=True, default='10000000123', max_length=15, unique=True, verbose_name='\u5546\u6237\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u5546\u6237\u540d\u79f0')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('key', models.CharField(default='', max_length=200, verbose_name='\u5bc6\u94a5')),
                ('expiretime', models.CharField(default='3600', max_length=6, verbose_name='\u6709\u6548\u65f6\u95f4')),
                ('daily_maxcount', models.IntegerField(default=100, verbose_name='\u6bcf\u65e5\u6700\u5927\u8bbf\u95ee\u6b21\u6570')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchant',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('paytime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('orderamount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u8ba2\u5355\u91d1\u989d')),
                ('payedamount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d')),
                ('payment_status', models.SmallIntegerField(verbose_name='\u652f\u4ed8\u72b6\u6001')),
                ('orderid', models.CharField(db_index=True, default=commom.models.gettimestamp, max_length=20, unique=True)),
            ],
            options={
                'ordering': ('orderid',),
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('orderid', models.CharField(max_length=30, verbose_name='\u8ba2\u5355\u4fe1\u606f')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'permissions': (('view', 'can view the available order'), ('change', 'can change the status')),
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('payment_id', models.CharField(db_index=True, default=commom.models.Paytimestamp, max_length=20, unique=True)),
                ('order_id', models.CharField(default='0', max_length=20)),
                ('payedamount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='\u652f\u4ed8\u91d1\u989d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('productid', models.CharField(db_index=True, default='0', max_length=18, unique=True, verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
                ('productname', models.CharField(max_length=30, null=True, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u4ea7\u54c1\u552e\u4ef7')),
                ('proddesc', models.CharField(max_length=500, null=True, verbose_name='\u4ea7\u54c1\u63cf\u8ff0')),
            ],
            options={
                'ordering': ('productid', 'mid'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('proj_id', models.CharField(db_index=True, default='', max_length=10)),
                ('proj_name', models.CharField(default='', max_length=128)),
                ('productid', models.CharField(default='0', max_length=15, verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
            ],
            options={
                'ordering': ('proj_id', 'mid'),
            },
        ),
        migrations.CreateModel(
            name='Submerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('subid', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='\u95e8\u5e97\u7f16\u53f7')),
            ],
            options={
                'verbose_name': 'Submerchant',
                'verbose_name_plural': 'Submerchant',
            },
        ),
        migrations.CreateModel(
            name='TokenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, verbose_name='\u7528\u6237token')),
                ('count', models.IntegerField(default=0, verbose_name='\u5df2\u8bbf\u95ee\u6b21\u6570')),
                ('max_count', models.IntegerField(default=100, verbose_name='\u6700\u5927\u8bbf\u95ee\u6b21\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='\u7528\u6237\u540d')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('phone', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('vertime', models.CharField(default='', max_length=200, verbose_name='\u9a8c\u8bc1\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Userdata',
                'verbose_name_plural': 'Merchant',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Project'),
        ),
    ]
