# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=30, verbose_name='\u8ba2\u5355\u4fe1\u606f')),
            ],
            options={
                'permissions': (('view', 'can view the available order'), ('change', 'can change the status')),
            },
        ),
    ]
