# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantid', models.CharField(db_index=True, default='10000000123', max_length=15, unique=True, verbose_name='\u5546\u6237\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u5546\u6237\u540d\u79f0')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('key', models.CharField(default='', max_length=200, verbose_name='\u5bc6\u94a5')),
                ('expiretime', models.CharField(default='3600', max_length=6, verbose_name='\u6709\u6548\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchant',
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='\u7528\u6237\u540d')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('phone', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('vertime', models.CharField(default='', max_length=200, verbose_name='\u9a8c\u8bc1\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Userdata',
                'verbose_name_plural': 'Merchant',
            },
        ),
    ]
