# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
        migrations.AddField(
            model_name='datapool',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant'),
        ),
    ]
