# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180408_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='user_id',
            field=models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
    ]
