# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-15 14:15
from __future__ import unicode_literals

import commom.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180414_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderamount',
            field=commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u8ba2\u5355\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payedamount',
            field=commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='package',
            name='high_bound',
            field=commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u4ef7\u683c\u4e0a\u9650'),
        ),
        migrations.AlterField(
            model_name='package',
            name='low_bound',
            field=commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u4ef7\u683c\u4e0b\u9650'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payedamount',
            field=commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productprice',
            field=commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u4ea7\u54c1\u552e\u4ef7'),
        ),
    ]
