# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-19 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180420_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ('itemid',), 'verbose_name': 'SKU\u5546\u54c1', 'verbose_name_plural': 'SKU\u5546\u54c1'},
        ),
    ]
