# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_merchant_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapool', models.TextField(verbose_name='\u6570\u636e\u6c60')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Merchant')),
            ],
        ),
    ]
