# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180408_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboRental',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.project',),
        ),
        migrations.CreateModel(
            name='ProductRental',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.project',),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(default=0, verbose_name='\u670d\u52a1\u72b6\u6001'),
        ),
    ]
