# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 06:34
from __future__ import unicode_literals

import commom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180420_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='attributes',
            field=commom.models.JSONField(default={}, verbose_name='\u4ea7\u54c1\u53c2\u6570'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='ptype',
            field=models.CharField(default='', max_length=20, verbose_name='\u578b\u53f7\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='comborental',
            name='create_user',
            field=models.CharField(default='user', max_length=10, verbose_name='\u521b\u5efa\u8005'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='proddesc',
            field=models.CharField(default='', max_length=500, verbose_name='\u4ea7\u54c1\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productname',
            field=models.CharField(default='', max_length=30, verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='productrental',
            name='create_user',
            field=models.CharField(default='user', max_length=10, verbose_name='\u521b\u5efa\u8005'),
        ),
    ]
