# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_datapool_merchantid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, verbose_name='\u7528\u6237token')),
                ('count', models.IntegerField(default=0, verbose_name='\u5df2\u8bbf\u95ee\u6b21\u6570')),
                ('max_count', models.IntegerField(default=100, verbose_name='\u6700\u5927\u8bbf\u95ee\u6b21\u6570')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='daily_maxcount',
            field=models.IntegerField(default=100, verbose_name='\u6bcf\u65e5\u6700\u5927\u8bbf\u95ee\u6b21\u6570'),
        ),
    ]
