# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-21 09:38
from __future__ import unicode_literals

import commom.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180420_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('mid', models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
                ('user_id', models.CharField(max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('paytime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('orderamount', commom.models.BillamountField(decimal_places=2, max_digits=12, verbose_name='\u8ba2\u5355\u91d1\u989d')),
                ('payedamount', commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d')),
                ('payment_status', models.SmallIntegerField(verbose_name='\u652f\u4ed8\u72b6\u6001')),
                ('orderid', models.CharField(db_index=True, default=commom.models.gettimestamp, editable=False, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '\u9500\u552e\u8ba2\u5355',
                'verbose_name_plural': '\u9500\u552e\u8ba2\u5355',
            },
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='userinfo',
        ),
        migrations.AddField(
            model_name='comborental',
            name='current_payamount',
            field=commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u5f53\u524d\u9700\u8981\u652f\u4ed8\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='daily_amount_pct',
            field=models.PositiveIntegerField(default=5, verbose_name='\u65e5\u79df\u91d1\u6bd4\u4f8b'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='guarantee_pct',
            field=models.PositiveIntegerField(default=70, verbose_name='\u62bc\u91d1\u6bd4\u4f8b'),
        ),
        migrations.AddField(
            model_name='productrental',
            name='current_payamount',
            field=commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u5f53\u524d\u9700\u8981\u652f\u4ed8\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='comboproj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RentalOrderid', to='crm.ComboRental'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='payedamount',
            field=commom.models.BillamountField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u652f\u4ed8\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RentalOrderid', to='crm.ProductRental'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='user_id',
            field=models.CharField(max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='comboproj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SaleOrderid', to='crm.ComboRental'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SaleOrderid', to='crm.ProductRental'),
        ),
    ]
