# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180421_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comborental',
            name='start_time',
            field=models.DateField(auto_now=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='productrental',
            name='start_time',
            field=models.DateField(auto_now=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='payment_status',
            field=models.SmallIntegerField(default=0, verbose_name='\u652f\u4ed8\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_status',
            field=models.SmallIntegerField(default=0, verbose_name='\u652f\u4ed8\u72b6\u6001'),
        ),
    ]
