# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171012_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f'),
        ),
    ]
