# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20180421_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comborental',
            name='end_time',
            field=models.DateField(default=b'2018-04-21', verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='productrental',
            name='end_time',
            field=models.DateField(default=b'2018-04-21', verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
