# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180330_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='gmt_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0d\u65f6\u95f4'),
        ),
    ]
