# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180421_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='comborental',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='package',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='productrental',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='submid',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='\u95e8\u5e97\u7f16\u53f7'),
        ),
    ]
