# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-21 14:12
from __future__ import unicode_literals

import commom.models
import crm.server_utils.base.FSM
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180421_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comborental',
            name='state',
        ),
        migrations.RemoveField(
            model_name='productrental',
            name='state',
        ),
        migrations.AddField(
            model_name='comborental',
            name='currsts',
            field=commom.models.StatusField(default=crm.server_utils.base.FSM.Start, verbose_name='\u670d\u52a1\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='productrental',
            name='currsts',
            field=commom.models.StatusField(default=crm.server_utils.base.FSM.Start, verbose_name='\u670d\u52a1\u72b6\u6001'),
        ),
    ]
