# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-30 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180331_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gmt_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='order',
            name='gmt_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
