# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20180331_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('payment_id', models.CharField(db_index=True, default=users.utils.gettimestamp, max_length=20, unique=True)),
                ('mid', models.CharField(default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('productid', models.CharField(db_index=True, max_length=18, unique=True, verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
                ('productname', models.CharField(max_length=30, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u4ea7\u54c1\u552e\u4ef7')),
                ('proddesc', models.CharField(max_length=500, verbose_name='\u4ea7\u54c1\u63cf\u8ff0')),
                ('mid', models.CharField(default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
            ],
            options={
                'ordering': ('productid',),
            },
        ),
        migrations.CreateModel(
            name='Submerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('subid', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='\u95e8\u5e97\u7f16\u53f7')),
                ('basemerchantid', models.CharField(default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7')),
            ],
            options={
                'verbose_name': 'Submerchant',
                'verbose_name_plural': 'Submerchant',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('orderid',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='mid',
            field=models.CharField(default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mid',
            field=models.CharField(default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
    ]
