# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180407_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ('productid', 'mid')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('proj_id', 'mid')},
        ),
        migrations.RemoveField(
            model_name='submerchant',
            name='basemerchantid',
        ),
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='mid',
            field=models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='order_id',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='productid',
            field=models.CharField(default='0', max_length=15, verbose_name='\u4ea7\u54c1\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='project',
            name='userid',
            field=models.CharField(default='0', max_length=15, verbose_name='\u7528\u6237\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='submerchant',
            name='mid',
            field=models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mid',
            field=models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='mid',
            field=models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='mid',
            field=models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='proddesc',
            field=models.CharField(max_length=500, null=True, verbose_name='\u4ea7\u54c1\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productid',
            field=models.CharField(db_index=True, default='0', max_length=18, unique=True, verbose_name='\u4ea7\u54c1\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productname',
            field=models.CharField(max_length=30, null=True, verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mid',
            field=models.CharField(db_index=True, default=b'100000000000001', max_length=15, verbose_name='\u603b\u5e97\u7f16\u53f7'),
        ),
    ]
